#targets:
#  code_generators:code_generators:
#    builders:
#      code_generators|copyBuilder:
#        enabled: True


# build配置
builders:
  copyBuilder:
    import: 'package:dart_command/src/code_generators.dart'
    builder_factories:  ['copyBuilder']
    build_extensions:
      .txt:
        -  .copy.txt
    build_to: source
    auto_apply: root_package