name: dart_command
description: dart command for process something.
version: 0.0.1
# homepage: https://www.example.com

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  console: ^3.0.0
  process_run: ^0.11.2+8
  dio: ^3.0.10
  build: ^1.6.2

dev_dependencies:
  pedantic: ^1.9.0
  build_config: ^0.4.5
  build_runner: ^1.11.0
  test: ^1.14.4

executables:
  dart_command:
